config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :like_reviews
    end
    collection do
      get :search
    end
  end
    
  resources :reviews, only: [:index, :new, :create, :destroy]
  resources :likes,only: [:create, :destroy]
  
  resources :products, only: [:id, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  counter_culture :review
  validates :user_id, presence: true
  validates :review_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image_product_sum, ImagesUploader
  mount_uploader :image_product_hed, ImagesUploader
  
  mount_uploader :evaluation, ImagesUploader
  
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  
  validates :product, presence: true
  validates :point, presence: true
  validates :content, presence: true
  validates :user,
    uniqueness: {
      scope: [:product],
      message: "はこの商品の口コミをすでに投稿しています。"
    }
    
    
  has_many :likes, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  
  mount_uploader :image_user, ImagesUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  enum sex: { male: 1, female: 2 }
  validates :age, numericality: { greater_than_or_equal_to: 18 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false,message: "すでに登録されています。" }
  has_secure_password
  
  has_many :reviews
  
  has_many :likes, dependent: :destroy
  has_many :like_reviews, through: :likes, source: :review
  
  def like(review)
    self.likes.find_or_create_by(review_id: review.id)
  end

  def unlike(review)
    like = self.likes.find_by(review_id: review.id)
    like.destroy if like
  end
  
  def like_review?(review)
    self.like_reviews.include?(review)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_reviews = user.reviews.count
    @count_like_reviews = user.like_reviews.count
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in

  def create
    @review = Review.find(params[:review_id])
    unless current_user.like_review?(@review)
      current_user.like(@review)
      @review.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end

  def destroy
    @review = Like.find(params[:id]).review
    if current_user.like_review?(@review)
      current_user.unlike(@review)
      @review.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page])
    averages(@product)
    
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.order('created_at DESC').page(params[:page])
    averages(@product)
    
  end

  def averages(product)
    @average_review = Review.group(:product_id).average(:point)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    @reviews = Review.all.page(params[:page])
  end
  
  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.order('created_at DESC').page(params[:page])
  end
  
  def new
    @review = Review.new
    @user = current_user
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if !@review
      flash[:success] = '口コミはすでに投稿されています。'
      redirect_to root_url
    end
    
    if  @review.save
      flash[:success] = '口コミを投稿しました。'
      redirect_to root_url
    else
      @reviews = current_user.reviews.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '口コミの投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @review.destroy
    flash[:success] = '口コミを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def review_params
    params.require(:review).permit(:product_id, :point, :content)
  end

  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    #@products = Product.all.page(params[:page])
    @products_shanpoo = Product.where(junre: 1)
    @products_tonic = Product.where(junre: 2)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order('created_at DESC').page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
 
    #編集しようとしてるユーザーがログインユーザーとイコールかをチェック
  if current_user == @user
    
    if params[:image_user]
      @user.image = "#{@user.id}.jpg"
      image = params[:image_user]
      File.binwrite("user_images/#{@user.image}", image.read)
      flash[:success] = '画像を保存しました。'
    end
 
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を編集しました。'
      render :edit
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end   
 
  else
    redirect_to root_url
  end
   
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def like_reviews
    @user = User.find(params[:id])
    @like_reviews = @user.like_reviews.page(params[:page])
    counts(@user)
  end
  
  private
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce, :image_user, :age, :sex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div class="alert alert-warning">
    <ul>
      
<% model.errors.full_messages.each do |message| %>

        <li>
<%= message %>
</li>
      
<% end %>

    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-<%= message_type %>"><%= message %></div>

<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container1">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">BIHATU</a>
      </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'ユーザー一覧', users_path %></li>
            <li><%= link_to '育毛剤一覧', products_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Kuchikomis</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Ravi+Prakash" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">
    
    
    <link rel="stylesheet" type="text/scss" href="slick.scss"/>
    <link rel="stylesheet" type="text/scss" href="slick-theme.scss"/>

    <link rel="stylesheet" type="text/css" href=" review.css">

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  
  
  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>


      <%= render 'layouts/flash_messages' %>

      <%= yield %>
   
  

  </body>
  
  
</html>

app/views/likes/_like_button.html.erb
  <span class="like">
    <% if current_user.like_review?(review) %>
      <%= form_for(current_user.likes.find_by(review_id: review.id), method: :delete, remote: true) do |f| %>
        <%= button_tag(class: "btn btn-default btn-xs") do %>
          <%= content_tag :span, "#{review.likes_count}", class: "glyphicon glyphicon-heart" %>
        <% end %>
      <% end %>
    <% else %>
      <%= form_for(current_user.likes.build, remote: true) do |f| %>
        <div><%= hidden_field_tag :review_id, review.id %></div>
        <%= button_tag(class: "btn btn-default btn-xs") do %>
          <%= content_tag :span, "#{review.likes_count}", class: "glyphicon glyphicon-heart-empty" %>
        <% end %>
      <% end %>
    <% end %>
  </span>

app/views/likes/create.js.erb
$("#review-<%= @review.id %> .like").html("<%= escape_javascript(render "likes/like_button", review: @review) %>");

app/views/likes/destroy.js.erb
$("#review-<%= @review.id %> .like").html("<%= escape_javascript(render "likes/like_button", review: @review) %>");

app/views/products/_products.html.erb
<% if products.any? %>
  <div id="container1">
    
  <ul class="media-list">
    <% products.each do |product| %>
      <li class="media">
        <div class="media-left">
          <% if product.image_product_sum.present? %>
            <%= image_tag product.image_product_sum.thumb.url %>
          <% else %>
            <div class="product">
              <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
            </div>
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= product.name %>
          </div>
          <div class="star-rating" data-score= <%= @average_review[product.id] %>></div>
          
          <div>
            <p><%= link_to 'View profile', product_path(product) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate products %>
  </div>
<% end %>

<script>
    $('.average-review-rating').raty({
        readOnly: true,
        path: '/assets/',
        score: function() {
            return $(this).attr('data-score')
        }
    });
</script>

<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  
  }
});
</script>

app/views/products/index.html.erb
<%= render 'products', products: @products %>

app/views/products/show.html.erb
<div id = "wrapper">
  <div id = "container">
    <div id = "content">
      <div id = "sidebar">
        
      </div>
      
        
        
        
      <div id = "main">
        <h1 class = "pageTitle">
          <%= @product.name %>の口コミ一覧
        </h1>
        <div class="image-top">
          <%= image_tag @product.image_product_hed.url %>
        </div>
        
        <h2 class = "school-category-title stripe">
          おすすめ度平均
        </h2>
        <div class="star-rating" data-score= <%= @average_review[@product.id] %>></div>
        
        <h2 class="school-category-title stripe">
          総合評価
        </h2>
          <%= @product.score %>
          <div class="image-top1">
            <%= image_tag @product.evaluation.url %>
          </div>        
          
        <h2 class="school-category-title stripe">
          商品価格
        </h2>
        <%= @product.price %>
        
        <h2 class="school-category-title stripe">
          商品概要
        </h2>
        <%= @product.introduce %>
        
        <h2 class="school-category-title stripe">
          内容量
        </h2>
        <%= @product.capacity %>
        
        <h2 class="school-category-title stripe">
          <%= @product.name %>の口コミ一覧
        </h2>
        
        <% if @reviews.any? %>
          <% @reviews.each do |review| %>
          <div id="review-<%= review.id %>" data-review-id="<%= review.id %>">
            <div class = "block">
              <div>
                <article class = "henry post">
                  <h2 class = "review-content-title">
                    <span class = "review-index-img">
                      <% if review.user.image_user.present? %>
                        <%= image_tag review.user.image_user.thumb.url %>
                      <% else %>
                        <div class="user">
                          <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
                        </div>
                      <% end %>
                    </span>
                    <span>
                      <%= review.user.name %>さんの口コミ
                    </span>
                  </h2>
                  <div class = "review-content">
                    <h3>おすすめ度</h3>
                    <div class="star-rating" data-score= <%= review.point %>></div>
                  </div>
                  <div class = "review-content">
                    <h3>評価理由</h3>
                    <%= review.content %>>
                  </div>
                <%= render "likes/like_button", review: review %>
                </article>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
      
      
      
    </div>
  </div>
</div>
          
        
          
     
<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  
  }
});
</script>

app/views/reviews/_reviews.html.erb
<div id="container">
  <div id="content">
    <div id="main">
      <% reviews.each do |review| %>
        <article class = "henry post">
          <h2 class = "review-content-title">
            <span class = "review-index-img">
              <% if review.user.image_user.present? %>
                <%= image_tag review.user.image_user.thumb.url %>
              <% else %>
                <div class="user">
                  <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
                </div>
              <% end %>
            </span>
            <%= review.user.name %>
          </h2>
          <div class = "review-content">
            <h3>おすすめ度</h3>
            <div class="star-rating" data-score= <%= review.point %>></div>
          </div>
        
          <div class = "review-content">
            <h3>評価理由</h3>
            <%= review.content %>>
          </div>
        </article>
      <% end %>
    </div>
  </div>
</div>

  
<script>
$('#star6').raty({
  readOnly: true,
  score: 4
});

$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  
  }
});
</script>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/index.html.erb
<%= render 'reviews', reviews: @reviews %>

app/views/reviews/new.html.erb
<%= javascript_include_tag 'jquery.raty.js' %>
<div id="wrapper">
  <div id="container">
    <div id="content">
      <div id="sidebar">
            
      </div>
      <div id="main">
        <div class="breadcrumbs"><a href="/">TOP</a><%= link_to @user.name+'さんのマイページ', user_path(current_user) %><span class="current">クチコミ投稿</span></div>
            
          <h5 class="pageTitle">
            クチコミ投稿
          </h5>
          
            <%= form_for(@review) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>

            <div class="form-group">
              <%= f.label :商品 %><br>
              <%= f.collection_select :product_id, Product.all, :id, :name,:prompt => "なんか選んでよ" %>
            </div>   
              
            <div class="form-group">
              <div id="star">
                <%= f.label :star %><br>
                <%= f.hidden_field :point, id: :review_point %>
              </div>
            </div>
            
            <div class="form-group">
              <%= f.label :評価理由 %><br>
              <%= f.text_area :content, class: 'form-control',placeholder:"例：頭皮の炎症が収まり、髪がサラサラになりました！" , rows: 5 %>
            </div>
        
            <%= f.submit '送信', class: 'btn btn-primary btn-block' %>

            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>



<script>
$("#hoge").css("color","red")
  
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  scoreName: 'review[point]' ,
});

</script>

app/views/toppages/index.html.erb
<% if logged_in? %>
  
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>


<div class="image-top">
  <a href="#"><%=  image_tag("/美髪 .png") %></a>
</div>

<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1><div class="sample4">あなたに最適なシャンプーを。</div></h1>
        
        <p><div class="sample4">自分に合ったシャンプーを見つけられるサイトです。</div></p>
        
        <div class="text-center">
          <%= link_to '口コミを投稿する', new_review_path, class: 'btn btn-lg btn-primary' %>
          <%= link_to '口コミ一覧を見る', reviews_path, class: 'btn btn-lg btn-primary' %>
          <%= link_to '商品別の口コミを見る', "#school_index", class: 'btn btn-lg btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>



<div id="school_index">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading" style="color:#000">商品別クチコミ</h2>
        <p>ログインなしで閲覧可能です。</p>
      </div>
      <div class="text-center">
        <div class="mx-auto text-center">
          <div class="top-school-list" ontouchstart="">
            <% @products_shanpoo.each do |product| %>
              <a class="js-scroll-trigger" href="/reviews/runteq">
                <div class="elem top-school isAnimate">
                  <div class="school-back">
                    <%= image_tag product.image_product_hed.url  %>
                    <p class="school-content"><%= product.name %></p>
                  </div>
                  <p class="school-content"><%= product.name %></p>
                </div>
              </a>  
            <% end %>
          </div>
          <div class="top-school-list" ontouchstart="">
            <% @products_tonic.each do |product| %>
              <a class="js-scroll-trigger" href="/reviews/runteq">
                <div class="elem top-school isAnimate">
                  <div class="school-back">
                    <%= image_tag product.image_product_hed.url  %>
                    <p class="school-content"><%= product.name %></p>
                  </div>
                  <p class="school-content"><%= product.name %></p>
                </div>
              </a>  
            <% end %>
          </div>
        </div>
      </div>    
    </div>
  </div>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading">お問い合わせ</h2>
          <hr class="my-4">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 mr-auto text-center">
          <a href="https://twitter.com/share?url=https://www.escola-pro.com&amp;hashtags=[Escola]" target="_blank" data-show-count="false"><i class="fab fa-twitter fa-3x mb-3"></i>
          <i class="fa fa-envelope-o fa-3x mb-3 text-color sr-contact"></i>
          </a>
          <p>
            <a href="https://twitter.com/escola60630755?lang=ja" target="_blank" class="text-color">Escola 公式アカウント</a>
          </p>
          <p class="mb-5 text-color">無料でオンライン、オフラインでプログラミングスクールのご相談に乗ります！</p>
          <p class="mb-5 text-color">以下のTwitterアカウントDMからお気軽にどうぞ！</p>
        </div>
        <div class="col-lg-12 mr-auto text-center">
          <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true" class="twitter-timeline twitter-timeline-rendered" style="position: static; visibility: visible; display: inline-block; width: 300px; height: 500px; padding: 0px; border: none; max-width: 100%; min-width: 180px; margin-top: 0px; margin-bottom: 0px; min-height: 200px;" data-widget-id="profile:escola60630755" title="Twitterタイムライン"></iframe>
          <script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>
    </div>
  </section>

  <footer class="footer">
    <ul>
      <li><a href="/terms">利用規約</a></li>
      <li><a href="/privacies">プライバシーポリシー</a></li>
    </ul>
  </footer>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="container1">
  <ul class="media-list">
    
    <% users.each do |user| %>

      <li class="media">
        <div class="media-left">
          <% if user.image_user.present? %>
            <%= image_tag user.image_user.thumb.url %>
          <% else %>
            <div class="user">
              <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
            </div>
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p>
              <%= link_to 'View profile', user_path(user) %>
            </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/like_reviews.html.erb
<div id="wrapper">
  <div class="container1">
    <div id="content">
      <div id="sidebar">
        <h5 class="sidebarTitle">メニュー</h5>
        <div class="sidebarList">
          <ul>
            <li>
              <i class="fas fa-edit"></i><%= link_to 'ユーザー情報編集', edit_user_path(@user) %>
            </li>
            <li>
              <i class="fas fa-portrait"></i><a href="/reviews/new">商品の口コミを投稿する</a></li>
            </li>
            <li>
              <i class="fas fa-heart"></i><%= link_to 'いいねした口コミ', like_reviews_user_path(@user) %>
            </li>
          </ul>
        </div>
      </div>
      <div id="main1">
        <div class="breadcrumbs"><a href="/">TOP</a><span class="current"><%= @user.name %></span></div>
        
          <h5 class="pageTitle">
            投稿一覧
          <span><%= @user.name %>さんがいいねしたクチコミです</span>
          </h5>
          
          
          <% if @like_reviews.any? %>
          <% @like_reviews.each do |review| %>
          <div id="review-<%= review.id %>" data-review-id="<%= review.id %>">
            <div class = "block">
              <div>
                <article class = "henry post">
                  <h2 class = "review-content-title">
                    <span class = "review-index-img">
                      <% if review.user.image_user.present? %>
                        <%= image_tag review.user.image_user.thumb.url %>
                      <% else %>
                        <div class="user">
                          <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
                        </div>
                      <% end %>
                    </span>
                    <span>
                      <%= review.user.name %>さんの口コミ
                    </span>
                  </h2>
                  <div class = "review-content">
                    <h3>おすすめ度</h3>
                    <div class="star-rating" data-score= <%= review.point %>></div>
                  </div>
                  <div class = "review-content">
                    <h3>評価理由</h3>
                    <%= review.content %>>
                  </div>
                <%= render "likes/like_button", review: review %>
                </article>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
          
          
        </div>
      </div>
    </div>
  </div>
</div>


<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  
  }
});
</script>

app/views/users/show.html.erb
<div id="wrapper">
  <div class="container1">
    <div id="content">
      <div id="sidebar">
        <h5 class="sidebarTitle">メニュー</h5>
        <div class="sidebarList">
          <ul>
            <li>
              <i class="fas fa-edit"></i><%= link_to 'ユーザー情報編集', edit_user_path(@user) %>
            </li>
            <li>
              <i class="fas fa-portrait"></i><a href="/reviews/new">商品の口コミを投稿する</a></li>
            </li>
            <li>
              <i class="fas fa-heart"></i><%= link_to 'いいねした口コミ', like_reviews_user_path(@user) %>
            </li>
          </ul>
        </div>

      </div>
      <div id="main1">
        <div class="breadcrumbs"><a href="/">TOP</a><span class="current"><%= @user.name %></span></div>
        
          <h5 class="pageTitle">
            投稿一覧
          <span><%= @user.name %>さんの投稿したクチコミです</span>
          </h5>
          
          
          <% if @reviews.any? %>
          <% @reviews.each do |review| %>
          <div id="review-<%= review.id %>" data-review-id="<%= review.id %>">
            <div class = "block">
              <div>
                <article class = "henry post">
                  <h2 class = "review-content-title">
                    <span class = "review-index-img">
                      <% if review.user.image_user.present? %>
                        <%= image_tag review.user.image_user.thumb.url %>
                      <% else %>
                        <div class="user">
                          <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
                        </div>
                      <% end %>
                    </span>
                    <span>
                      <%= review.user.name %>さんの口コミ
                    </span>
                  </h2>
                  <div class = "review-content">
                    <h3>おすすめ度</h3>
                    <div class="star-rating" data-score= <%= review.point %>></div>
                  </div>
                  <div class = "review-content">
                    <h3>評価理由</h3>
                    <%= review.content %>>
                  </div>
                <%= render "likes/like_button", review: review %>
                </article>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
          
          
        </div>
      </div>
    </div>
  </div>
</div>


<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  
  }
});
</script>